In [28]:
import pandas as pd
import numpy as np

In [4]:
print("Loading data...")

Loading data...

In [14]:
from pathlib import Path

candidate_paths = [
	#Path("data/twitter_sentiment.csv"),
	Path("../data/twitter_sentiment.csv")
]

csv_path = next((p for p in candidate_paths if p.exists()), None)

if csv_path is None:
	print("Dataset not found. Checked:")
	for p in candidate_paths:
		print(f"- {p.resolve()}")
	df = pd.DataFrame()
else:
	df = pd.read_csv(csv_path)
	print(f"Data loaded successfully from: {csv_path.resolve()}")

Data loaded successfully from: D:\Abdul Wasay\Text-Sentiment-Predictor-AWS\data\twitter_sentiment.csv

In [15]:
df

                                               clean_text  category
0       when modi promised “minimum government maximum...      -1.0
1       talk all the nonsense and continue all the dra...       0.0
2       what did just say vote for modi  welcome bjp t...       1.0
3       asking his supporters prefix chowkidar their n...       1.0
4       answer who among these the most powerful world...       1.0
...                                                   ...       ...
162975  why these 456 crores paid neerav modi not reco...      -1.0
162976  dear rss terrorist payal gawar what about modi...      -1.0
162977  did you cover her interaction forum where she ...       0.0
162978  there big project came into india modi dream p...       0.0
162979  have you ever listen about like gurukul where ...       1.0

[162980 rows x 2 columns]

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 162980 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   clean_text  162976 non-null  str
 1   category    162973 non-null  float64
dtypes: float64(1), str(1)
memory usage: 2.5 MB

In [17]:
df.describe()

            category
count  162973.000000
mean        0.225436
std         0.781279
min        -1.000000
25%         0.000000
50%         0.000000
75%         1.000000
max         1.000000

In [18]:
df.isnull().sum()

clean_text    4
category      7
dtype: int64

In [19]:
df.dropna(inplace=True)

In [20]:
df.isnull().sum()

clean_text    0
category      0
dtype: int64

In [25]:
counter = df["category"].value_counts()
counter

category
 1.0    72249
 0.0    55211
-1.0    35509
Name: count, dtype: int64

In [30]:
df.info()

<class 'pandas.DataFrame'>
Index: 162969 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   clean_text  162969 non-null  str
 1   category    162969 non-null  float64
dtypes: float64(1), str(1)
memory usage: 3.7 MB

In [36]:
# Convert the column to object type to allow string values
df['category'] = df['category'].astype('object')

# Convert numeric categories to string labels
df.loc[df['category'] == 1.0, 'category'] = "positive"
df.loc[df['category'] == 0.0, 'category'] = "neutral"
df.loc[df['category'] == -1.0, 'category'] = "negative"

In [37]:
df["category"].value_counts()

category
positive    72249
neutral     55211
negative    35509
Name: count, dtype: int64

In [53]:
df.info()

<class 'pandas.DataFrame'>
Index: 162969 entries, 0 to 162979
Data columns (total 2 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   clean_text  162969 non-null  str
 1   category    162969 non-null  object
dtypes: object(1), str(1)
memory usage: 3.7+ MB

In [50]:
df

                                               clean_text  category
0       when modi promised “minimum government maximum...  negative
1       talk all the nonsense and continue all the dra...   neutral
2       what did just say vote for modi  welcome bjp t...  positive
3       asking his supporters prefix chowkidar their n...  positive
4       answer who among these the most powerful world...  positive
...                                                   ...       ...
162975  why these 456 crores paid neerav modi not reco...  negative
162976  dear rss terrorist payal gawar what about modi...  negative
162977  did you cover her interaction forum where she ...   neutral
162978  there big project came into india modi dream p...   neutral
162979  have you ever listen about like gurukul where ...  positive

[162969 rows x 2 columns]

In [52]:
df.to_csv("../data/preprocessed_twitter_sentiment.csv", index=False)